"""user refact

Revision ID: 6e2867292646
Revises: 937b109bd980
Create Date: 2025-07-19 22:40:36.530594

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6e2867292646"
down_revision: Union[str, None] = "937b109bd980"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_nickname_key", "users", type_="unique")
    op.drop_column("users", "lastname")
    op.drop_column("users", "firstname")
    op.drop_column("users", "nickname")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "nickname", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "firstname", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "lastname", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
    )
    op.create_unique_constraint("users_nickname_key", "users", ["nickname"])
    # ### end Alembic commands ###
